### ISSUE TITLE
normalize images by number of cells

### ISSUE THREAD

**Issue by nbathreya** [czbiohub-sf/PhenoSight#19] opened 2023-08-18 20:29 UTC
The z-score might be getting influenced by the number of cells in each condition. Normalizing the feature by the number of cells according to each condition image would result in more accurate z-score.

**Comment by mattersoflight** [comment] 2023-10-04 23:40
Closing this, because it is a duplicate of #28 and #30

**Closed by mattersoflight** 2023-10-04 23:40 UTC
Labels: bug
